# Generated by Django 6.1 on 2026-08-17 09:05

import django.db.models.deletion
import users.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_demorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(help_text="Which agent this run belongs to, e.g. 'skeleton' or 'proposal'.", max_length=64)),
                ('thread_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('awaiting_input', 'Awaiting input'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_threads', to='users.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'agent', 'status'], name='agents_agen_organis_748db4_idx')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
