# Generated by Django 6.1 on 2026-08-17 10:23

import django.db.models.deletion
import users.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('bookings', '0087_orgsettings_proposal_agent_enabled_and_more'),
        ('users', '0008_demorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('questions_pending', 'Questions pending'), ('drafting', 'Drafting'), ('drafted', 'Drafted'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='questions_pending', max_length=20)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_draft', to='agents.agentthread')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to='bookings.lead')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to='users.organisation')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts', to='bookings.quote')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'lead', 'status'], name='agents_prop_organis_2fa787_idx')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
