# Generated by Django 6.0.1 on 2026-02-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0004_eventdishcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='events.event'),
        ),
    ]
