# Generated by Django 6.0.1 on 2026-03-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('dishes', '0001_initial'),
        ('events', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentreservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='events.event'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='events.event'),
        ),
        migrations.AddField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='bookings.account'),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='bookings.budgetrangeoption'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.invoice'),
        ),
        migrations.AddField(
            model_name='quote',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='bookings.account'),
        ),
        migrations.AddField(
            model_name='quote',
            name='based_on_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='menus.menutemplate'),
        ),
        migrations.AddField(
            model_name='quote',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='dishes.dish'),
        ),
        migrations.AddField(
            model_name='quote',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='events.event'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='bookings.lead'),
        ),
        migrations.AddField(
            model_name='quote',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='bookings.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='bookings.quote'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='equipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='bookings.equipmentitem'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='labor_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='bookings.laborrole'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='dishes.dish'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bookings.quote'),
        ),
        migrations.AddField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='events.event'),
        ),
        migrations.AddField(
            model_name='shift',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='bookings.laborrole'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='bookings.laborrole'),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='bookings.staffmember'),
        ),
        migrations.AddField(
            model_name='quote',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='bookings.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentreservation',
            unique_together={('event', 'equipment')},
        ),
    ]
