# Generated by Django 6.0.1 on 2026-02-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_quote_event'),
        ('dishes', '0006_remove_protein_per_gram'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='based_on_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='menus.menutemplate'),
        ),
        migrations.AddField(
            model_name='quote',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='dishes.dish'),
        ),
    ]
