# Generated by Django 6.0.1 on 2026-02-17 14:45

import django.db.models.deletion
from django.db import migrations, models


INITIAL_BUDGET_RANGES = [
    {'label': 'Under £1,000', 'sort_order': 1},
    {'label': '£1,000 – £5,000', 'sort_order': 2},
    {'label': '£5,000 – £10,000', 'sort_order': 3},
    {'label': '£10,000+', 'sort_order': 4},
]

OLD_VALUE_TO_LABEL = {
    'under_1k': 'Under £1,000',
    '1k_5k': '£1,000 – £5,000',
    '5k_10k': '£5,000 – £10,000',
    '10k_plus': '£10,000+',
}


def seed_budget_ranges_and_convert(apps, schema_editor):
    BudgetRangeOption = apps.get_model('bookings', 'BudgetRangeOption')
    SiteSettings = apps.get_model('bookings', 'SiteSettings')

    # Seed budget range options
    label_to_pk = {}
    for data in INITIAL_BUDGET_RANGES:
        obj, _ = BudgetRangeOption.objects.get_or_create(
            label=data['label'],
            defaults={'sort_order': data['sort_order'], 'is_active': True},
        )
        label_to_pk[data['label']] = obj.pk

    # Seed default site settings
    SiteSettings.objects.get_or_create(pk=1, defaults={
        'currency_symbol': '£',
        'currency_code': 'GBP',
    })

    # Convert old string values to FK references
    db_alias = schema_editor.connection.alias
    from django.db import connections
    with connections[db_alias].cursor() as cursor:
        cursor.execute("SELECT id, budget_range FROM bookings_lead WHERE budget_range IS NOT NULL AND budget_range != ''")
        rows = cursor.fetchall()
        for lead_id, old_value in rows:
            label = OLD_VALUE_TO_LABEL.get(old_value)
            if label and label in label_to_pk:
                cursor.execute(
                    'UPDATE bookings_lead SET budget_range = %s WHERE id = %s',
                    [str(label_to_pk[label]), lead_id],
                )
            else:
                cursor.execute(
                    'UPDATE bookings_lead SET budget_range = NULL WHERE id = %s',
                    [lead_id],
                )
        # Clear empty strings to NULL
        cursor.execute("UPDATE bookings_lead SET budget_range = NULL WHERE budget_range = ''")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_quote_menu_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRangeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display label, e.g. "£1,000 – £5,000"', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='£', help_text='e.g. £, $, €', max_length=10)),
                ('currency_code', models.CharField(default='GBP', help_text='e.g. GBP, USD, EUR', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        # First make the CharField nullable so we can convert empty strings to NULL
        migrations.AlterField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        # Seed data and convert old string values
        migrations.RunPython(seed_budget_ranges_and_convert, migrations.RunPython.noop),
        # Now convert to FK
        migrations.AlterField(
            model_name='lead',
            name='budget_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='bookings.budgetrangeoption'),
        ),
    ]
