# Generated by Django 6.0.1 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_lead_assigned_to_productline_lead_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_date',
            field=models.DateField(blank=True, help_text='Date the lead was originally generated (e.g. from ad platform)', null=True),
        ),
    ]
