# Generated by Django 6.0.1 on 2026-02-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_configurable_budget_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='bookings.contact'),
        ),
        migrations.AddField(
            model_name='quote',
            name='venue_address',
            field=models.TextField(blank=True, help_text='Freeform address for ad-hoc venues'),
        ),
    ]
