# Generated by Django 6.0.1 on 2026-02-27 16:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_quote_contact_venue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Food/menu price per head', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_price_per_head',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default food price per head for new quotes/events', max_digits=10),
        ),
    ]
