# Generated by Django 6.0.1 on 2026-03-05 19:17

from django.db import migrations


def seed_choices(apps, schema_editor):
    EventTypeOption = apps.get_model('bookings', 'EventTypeOption')
    SourceOption = apps.get_model('bookings', 'SourceOption')
    ServiceStyleOption = apps.get_model('bookings', 'ServiceStyleOption')
    LeadStatusOption = apps.get_model('bookings', 'LeadStatusOption')

    event_types = [
        ('wedding', 'Wedding'),
        ('corporate', 'Corporate Event'),
        ('birthday', 'Birthday Party'),
        ('funeral', 'Funeral / Wake'),
        ('religious', 'Religious Event'),
        ('social', 'Social Gathering'),
        ('other', 'Other'),
    ]
    for i, (value, label) in enumerate(event_types):
        EventTypeOption.objects.get_or_create(value=value, defaults={'label': label, 'sort_order': i})

    sources = [
        ('website', 'Website'),
        ('referral', 'Referral'),
        ('phone', 'Phone'),
        ('email', 'Email'),
        ('social', 'Social Media'),
        ('walk_in', 'Walk-in'),
        ('repeat', 'Repeat Customer'),
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    ]
    for i, (value, label) in enumerate(sources):
        SourceOption.objects.get_or_create(value=value, defaults={'label': label, 'sort_order': i})

    service_styles = [
        ('buffet', 'Buffet'),
        ('plated', 'Plated / Sit-down'),
        ('stations', 'Food Stations'),
        ('family_style', 'Family Style'),
        ('boxed', 'Boxed / Individual'),
        ('canapes', 'Canapés'),
        ('mixed', 'Mixed Service'),
    ]
    for i, (value, label) in enumerate(service_styles):
        ServiceStyleOption.objects.get_or_create(value=value, defaults={'label': label, 'sort_order': i})

    lead_statuses = [
        ('new', 'New'),
        ('contacted', 'Contacted'),
        ('qualified', 'Qualified'),
        ('converted', 'Converted'),
        ('lost', 'Lost'),
    ]
    for i, (value, label) in enumerate(lead_statuses):
        LeadStatusOption.objects.get_or_create(value=value, defaults={'label': label, 'sort_order': i})


def reverse_seed(apps, schema_editor):
    apps.get_model('bookings', 'EventTypeOption').objects.all().delete()
    apps.get_model('bookings', 'SourceOption').objects.all().delete()
    apps.get_model('bookings', 'ServiceStyleOption').objects.all().delete()
    apps.get_model('bookings', 'LeadStatusOption').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_eventtypeoption_leadstatusoption_servicestyleoption_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_choices, reverse_seed),
    ]
