# Generated by Django 6.0.1 on 2026-02-27 20:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_price_per_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='target_food_cost_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Target food cost as % of selling price (e.g. 30 means 30%)', max_digits=5),
        ),
    ]
