# Generated by Django 6.0.1 on 2026-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_seed_choice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='budget_range',
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='BudgetRangeOption',
        ),
    ]
