# Generated by Django 6.0.1 on 2026-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_sitesettings_target_food_cost_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='price_rounding_step',
            field=models.PositiveIntegerField(default=50, help_text='Round calculated prices to the nearest N (e.g. 50, 100). Set to 1 to disable rounding.'),
        ),
    ]
