# Generated by Django 6.0.1 on 2026-03-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_decouple_quotes_from_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY (UK / Europe)'), ('MM/DD/YYYY', 'MM/DD/YYYY (US)'), ('YYYY-MM-DD', 'YYYY-MM-DD (ISO)')], default='DD/MM/YYYY', help_text='Date display format across the application', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_change', 'Status Change'), ('assigned', 'Assigned'), ('won', 'Won'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
