# Generated by Django 6.0.3 on 2026-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_add_quote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='quotation_terms',
            field=models.TextField(blank=True, help_text='Terms & Conditions text printed on quotation PDFs.'),
        ),
    ]
