# Generated by Django 6.0.3 on 2026-03-12 10:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_add_quote_created_by'),
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='eventtypeoption',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='leadstatusoption',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='lostreasonoption',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='quote',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='servicestyleoption',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='sourceoption',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='venue',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='users.organisation'),
        ),
        migrations.AlterField(
            model_name='eventtypeoption',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadstatusoption',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lostreasonoption',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicestyleoption',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sourceoption',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='eventtypeoption',
            unique_together={('organisation', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='leadstatusoption',
            unique_together={('organisation', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='lostreasonoption',
            unique_together={('organisation', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='servicestyleoption',
            unique_together={('organisation', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='sourceoption',
            unique_together={('organisation', 'value')},
        ),
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='£', help_text='e.g. £, $, €', max_length=10)),
                ('currency_code', models.CharField(default='GBP', help_text='e.g. GBP, USD, EUR', max_length=10)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY (UK / Europe)'), ('MM/DD/YYYY', 'MM/DD/YYYY (US)'), ('YYYY-MM-DD', 'YYYY-MM-DD (ISO)')], default='DD/MM/YYYY', help_text='Date display format across the application', max_length=10)),
                ('timezone', models.CharField(default='Europe/London', max_length=50)),
                ('tax_label', models.CharField(default='VAT', help_text='e.g. VAT, Sales Tax, GST', max_length=20)),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), help_text='Default tax rate as decimal (e.g. 0.2000 = 20%)', max_digits=5)),
                ('default_price_per_head', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default food price per head for new quotes/events', max_digits=10)),
                ('target_food_cost_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Target food cost as % of selling price (e.g. 30 means 30%)', max_digits=5)),
                ('price_rounding_step', models.PositiveIntegerField(default=50, help_text='Round calculated prices to the nearest N (e.g. 50, 100). Set to 1 to disable rounding.')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Settings',
                'verbose_name_plural': 'Organisation Settings',
            },
        ),
    ]
