# Generated by Django 6.0.1 on 2026-03-12 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_add_quotation_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='guest_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Food/menu price per head', max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999'))]),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='price_rounding_step',
            field=models.PositiveIntegerField(default=50, help_text='Round calculated prices to the nearest N (e.g. 50, 100). Set to 1 to disable rounding.', validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
