# Generated by Django 6.0.1 on 2026-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_payment_amount_alter_quote_guest_count_and_more'),
        ('bookings', '0018_make_org_nonnull'),
    ]

    operations = [
    ]
