# Generated by Django 6.0.1 on 2026-03-12 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_eventtypeoption_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='quotation_terms',
            field=models.TextField(blank=True, help_text='Terms & Conditions text printed on quotation PDFs.'),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='price_rounding_step',
            field=models.PositiveIntegerField(default=50, help_text='Round calculated prices to the nearest N (e.g. 50, 100). Set to 1 to disable rounding.', validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
