# Generated by Django 6.0.1 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_lead_meal_type_quote_meal_type_mealtypeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='booking_date',
            field=models.DateField(blank=True, help_text='Date the client confirmed/booked', null=True),
        ),
    ]
