# Generated by Django 6.0.1 on 2026-03-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_quote_booking_date'),
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangementTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
                'unique_together': {('organisation', 'value')},
            },
        ),
    ]
