# Generated by Django 5.2.12 on 2026-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_quote_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='colour',
            field=models.CharField(default='#6B7280', help_text='Hex colour for calendar display', max_length=7),
        ),
    ]
