# Generated by Django 6.0.1 on 2026-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_beveragetypeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY (UK / Europe)'), ('MM/DD/YYYY', 'MM/DD/YYYY (US)'), ('YYYY-MM-DD', 'YYYY-MM-DD (ISO)'), ('DD MMM YYYY', 'DD MMM YYYY (e.g. 14 Mar 2026)'), ('DD MMM YY', 'DD MMM YY (e.g. 14 Mar 26)'), ('MMM DD, YYYY', 'MMM DD, YYYY (e.g. Mar 14, 2026)')], default='DD/MM/YYYY', help_text='Date display format across the application', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY (UK / Europe)'), ('MM/DD/YYYY', 'MM/DD/YYYY (US)'), ('YYYY-MM-DD', 'YYYY-MM-DD (ISO)'), ('DD MMM YYYY', 'DD MMM YYYY (e.g. 14 Mar 2026)'), ('DD MMM YY', 'DD MMM YY (e.g. 14 Mar 26)'), ('MMM DD, YYYY', 'MMM DD, YYYY (e.g. Mar 14, 2026)')], default='DD/MM/YYYY', help_text='Date display format across the application', max_length=20),
        ),
    ]
