# Generated by Django 5.2.12 on 2026-03-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_perf_indexes'),
        ('bookings', '0028_seed_workflow_options_only'),
    ]

    operations = [
    ]
