# Generated by Django 5.2.12 on 2026-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_merge_20260317_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='round_robin_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
