# Generated by Django 5.2.12 on 2026-03-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_productline_colour'),
        ('bookings', '0030_round_robin_index'),
    ]

    operations = [
    ]
