# Generated by Django 5.2.12 on 2026-03-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_merge_0025_productline_colour_0030_round_robin_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='account_org_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_org_assigned_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_org_event_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_org_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='quote_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='quote_org_event_date_idx',
        ),
        migrations.RemoveField(
            model_name='orgsettings',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='orgsettings',
            name='twilio_auth_token_encrypted',
        ),
        migrations.RemoveField(
            model_name='orgsettings',
            name='twilio_whatsapp_number',
        ),
    ]
