# Generated by Django 5.2.12 on 2026-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_remove_twilio_fields_from_orgsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='twilio_auth_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='twilio_whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Twilio WhatsApp sender number, e.g. +14155238886', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('received', 'Received'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='queued', max_length=15),
        ),
    ]
