# Generated by Django 5.2.12 on 2026-06-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_orgsettings_twilio_account_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
