# Generated by Django 5.2.12 on 2026-06-21 16:20

import django.core.validators
import django.db.models.deletion
import users.model_mixins
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_contact_address'),
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('rental', 'Rental'), ('labor', 'Labour'), ('fee', 'Fee'), ('discount', 'Discount')], default='rental', max_length=20)),
                ('default_unit', models.CharField(choices=[('per_guest', 'Per Guest'), ('per_hour', 'Per Hour'), ('flat', 'Flat Rate'), ('each', 'Each')], default='each', max_length=20)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as a quick checkbox when adding items')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_products', to='users.organisation')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
        migrations.CreateModel(
            name='AddOnVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_variants', to='users.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bookings.addonproduct')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
