# Generated by Django 5.2.12 on 2026-06-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0039_booking_line_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beveragetypeoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='beveragetypeoption',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='ArrangementTypeOption',
        ),
        migrations.DeleteModel(
            name='BeverageTypeOption',
        ),
    ]
