# Generated by Django 5.2.12 on 2026-06-22 15:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_product_price(apps, schema_editor):
    """Seed each product's base price from its first variant, so existing simple
    products carry a price directly (variants can then inherit or override)."""
    AddOnProduct = apps.get_model('bookings', 'AddOnProduct')
    db = schema_editor.connection.alias
    for product in AddOnProduct.objects.using(db).all():
        first = product.variants.order_by('sort_order', 'pk').first()
        if first is not None and first.unit_price is not None:
            product.unit_price = first.unit_price
            product.save(update_fields=['unit_price'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_alter_beveragetypeoption_unique_together_and_more'),
    ]

    operations = [
        # All schema (DDL) changes first, then the data backfill — keeps Postgres
        # from hitting "pending trigger events" when DDL and data mix in one txn.
        migrations.AddField(
            model_name='addonproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Base price. Variants without their own price inherit this.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='addonvariant',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit the product price; set a value to override it.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(backfill_product_price, noop),
    ]
