# Generated by Django 5.2.12 on 2026-06-23 19:08

from django.db import migrations, models


COLORS = {
    'new': 'blue', 'contacted': 'amber', 'qualified': 'cyan',
    'proposal_sent': 'violet', 'won': 'green', 'lost': 'gray',
}


def backfill(apps, schema_editor):
    """Seed colour + semantic flags on existing orgs' lead statuses by their
    known default values, and guarantee every org has exactly one default stage."""
    LeadStatusOption = apps.get_model('bookings', 'LeadStatusOption')
    db = schema_editor.connection.alias
    rows = LeadStatusOption.objects.using(db)

    for value, color in COLORS.items():
        rows.filter(value=value).update(color=color)
    rows.filter(value='won').update(is_won=True)
    rows.filter(value='lost').update(is_lost=True)
    rows.filter(value='new').update(is_default=True)

    # Any org with no default (e.g. renamed 'new'): flag its first stage.
    org_ids = list(rows.values_list('organisation_id', flat=True).distinct())
    for org_id in org_ids:
        org_rows = rows.filter(organisation_id=org_id)
        if not org_rows.filter(is_default=True).exists():
            first = org_rows.order_by('sort_order', 'pk').first()
            if first is not None:
                first.is_default = True
                first.save(update_fields=['is_default'])

    # Neutral fallback colour for any status not in the known set.
    rows.filter(color='').update(color='slate')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatusoption',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leadstatusoption',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadstatusoption',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadstatusoption',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill, noop),
    ]
