# Generated by Django 5.2.12 on 2026-06-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0042_lead_status_color_and_flags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
