# Generated by Django 5.2.12 on 2026-06-25 16:50

import django.db.models.deletion
import users.model_mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0043_remove_sitesettings'),
        ('users', '0006_add_admin_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='commission_flat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission rate % on all won revenue (used when model is flat).', max_digits=5),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='commission_model',
            field=models.CharField(choices=[('flat', 'Flat rate'), ('accelerated', 'Accelerated (banded by target attainment)')], default='flat', help_text='Flat rate on all revenue, or accelerated bands keyed to target attainment.', max_length=20),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='target_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Period over which sales targets and commission are measured and reset.', max_length=20),
        ),
        migrations.CreateModel(
            name='CommissionBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_attainment_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Band starts at this % of target attainment (e.g. 0, 100, 120).', max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission rate % applied to revenue that falls in this band.', max_digits=5)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_bands', to='users.organisation')),
            ],
            options={
                'ordering': ['min_attainment_pct'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'min_attainment_pct'), name='uniq_org_commission_band_threshold')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue target per period for this salesperson.', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='users.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user'), name='uniq_org_user_sales_target')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
