# Generated by Django 5.2.12 on 2026-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0044_orgsettings_commission_flat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='commission_basis',
            field=models.CharField(choices=[('event_date', 'Event date (when the event takes place)'), ('booking_date', 'Booking date (when the event was confirmed)')], default='event_date', help_text='Which date attributes a confirmed event to a commission period.', max_length=20),
        ),
    ]
