# Generated by Django 5.2.12 on 2026-06-25 22:10

import django.db.models.deletion
import users.model_mixins
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0046_backfill_event_assigned_to'),
        ('users', '0006_add_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commission_model', models.CharField(choices=[('flat', 'Flat rate'), ('accelerated', 'Accelerated (banded by target attainment)')], default='flat', help_text='Flat rate, or accelerated bands keyed to target attainment.', max_length=20)),
                ('commission_flat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission rate % on all revenue (used when the model is flat).', max_digits=5)),
                ('is_default', models.BooleanField(default=False, help_text='Used for salespeople with no plan assigned (one per org).')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='commissionband',
            name='uniq_org_commission_band_threshold',
        ),
        migrations.AddField(
            model_name='commissionplan',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plans', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='commissionband',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='bookings.commissionplan'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='bookings.commissionplan'),
        ),
        migrations.AddConstraint(
            model_name='commissionband',
            constraint=models.UniqueConstraint(fields=('plan', 'min_attainment_pct'), name='uniq_plan_commission_band_threshold'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_org_commission_plan_name'),
        ),
    ]
