# Generated by Django 5.2.12 on 2026-06-26 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0048_default_commission_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January (calendar year)'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text="Month the financial year starts (1 = calendar year). Drives 'this year' and yearly targets.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
