# Generated by Django 5.2.12 on 2026-06-30 20:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_gender_split(apps, schema_editor):
    """Seed gents/ladies from the existing single guest_count (50/50, the same
    split the quote→event conversion already used). Idempotent + memory-safe."""
    Quote = apps.get_model('bookings', 'Quote')
    for q in Quote.objects.all().iterator():
        gc = q.guest_count or 0
        q.gents = gc // 2
        q.ladies = gc - q.gents
        q.save(update_fields=['gents', 'ladies'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0050_periodwise_sales_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='big_eaters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='big_eaters_percentage',
            field=models.FloatField(default=20.0, help_text='Percentage to increase all portions when big_eaters is on'),
        ),
        migrations.AddField(
            model_name='quote',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='gents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AddField(
            model_name='quote',
            name='guest_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='Whether tax applies to this booking'),
        ),
        migrations.AddField(
            model_name='quote',
            name='ladies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AddField(
            model_name='quote',
            name='meal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='setup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Food/menu price per head', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunPython(backfill_gender_split, migrations.RunPython.noop),
    ]
