# Generated by Django 5.2.12 on 2026-07-03 07:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0051_quote_booking_parity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestarget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue target for this rep in this period.', max_digits=14),
        ),
    ]
