# Generated by Django 5.2.12 on 2026-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0052_alter_salestarget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected on new bookings when not carried from a lead.'),
        ),
    ]
