# Generated by Django 5.2.12 on 2026-07-03 18:59

import django.core.validators
import django.db.models.deletion
import users.model_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0053_productline_is_default'),
        ('users', '0006_add_admin_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgsettings',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='orgsettings',
            name='twilio_auth_token_encrypted',
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='ai_followups_enabled',
            field=models.BooleanField(default=False, help_text='Let the AI agent draft WhatsApp follow-ups for stale leads (always reviewed before sending).'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='followup_max_drafts_per_lead',
            field=models.PositiveIntegerField(default=3, help_text='Never generate more than this many follow-up drafts for a single lead.', validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='followup_stale_hours',
            field=models.PositiveIntegerField(default=168, help_text='Hours a lead can sit untouched before the agent drafts a follow-up (default 168 = 7 days).', validators=[django.core.validators.MaxValueValidator(8760)]),
        ),
        migrations.CreateModel(
            name='FollowUpDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('body', models.TextField(help_text='The drafted message the agent proposes to send.')),
                ('reasoning', models.TextField(blank=True, default='', help_text='Short rationale the agent gave for this follow-up.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('sent', 'Approved & sent'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('model_used', models.CharField(blank=True, default='', max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_drafts', to='bookings.lead')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_drafts', to='users.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_followup_drafts', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_draft', to='bookings.whatsappmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='bookings_fo_organis_a2a6fd_idx'), models.Index(fields=['lead', 'status'], name='bookings_fo_lead_id_5374da_idx')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
