# Generated by Django 5.2.12 on 2026-07-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0054_backfill_booking_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='time_format',
            field=models.CharField(choices=[('24h', '24-hour (e.g. 19:00)'), ('12h', '12-hour AM/PM (e.g. 7:00 PM)')], default='24h', help_text='Time display format (12-hour AM/PM or 24-hour) across the application', max_length=3),
        ),
    ]
