# Generated by Django 5.2.12 on 2026-07-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0055_orgsettings_time_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Salesperson who owns this quote; drives commission attribution and carries to the event on conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
