# Generated by Django 5.2.12 on 2026-07-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0054_remove_orgsettings_twilio_account_sid_and_more'),
        ('bookings', '0056_quote_assigned_to'),
    ]

    operations = [
    ]
