# Generated by Django 5.2.12 on 2026-07-06 19:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0056_quote_assigned_to'),
        ('events', '0023_event_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BookingSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('signature_image', models.TextField(blank=True)),
                ('consent_text', models.TextField(blank=True)),
                ('agreed_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('agreed_guest_count', models.IntegerField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('signed_pdf', models.BinaryField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='events.event')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='bookings.quote')),
            ],
            options={
                'ordering': ['-signed_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('quote__isnull', False)), models.Q(('event__isnull', False), ('quote__isnull', True)), _connector='OR'), name='bookingsignature_exactly_one_parent')],
            },
        ),
    ]
