# Generated by Django 5.2.12 on 2026-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0057_merge_20260710_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='default_guest_profile',
            field=models.CharField(choices=[('gents', 'Standard (gents)'), ('ladies', 'Ladies')], default='gents', help_text='Portion rule applied to all guests when an event has no gents/ladies split', max_length=10),
        ),
    ]
