# Generated by Django 5.2.12 on 2026-07-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0058_orgsettings_default_guest_profile'),
        ('bookings', '0058_reassign_reminders_to_lead_owner'),
    ]

    operations = [
    ]
