# Generated by Django 5.2.12 on 2026-07-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0059_merge_20260712_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='', help_text='How to address the contact in messages (e.g. Ms Rizvi)', max_length=10),
        ),
    ]
