# Generated by Django 5.2.12 on 2026-07-17 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0062_split_existing_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='followup_max_drafts_per_lead',
            field=models.PositiveIntegerField(default=3, help_text="Stop after this many follow-ups have been SENT to one lead (dismissed drafts don't count).", validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
