# Generated by Django 5.2.12 on 2026-07-17 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0063_alter_orgsettings_followup_max_drafts_per_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgsettings',
            name='followup_stale_hours',
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='followup_gap_final_days',
            field=models.PositiveIntegerField(default=14, help_text='Days after the second (and any later) follow-up before the next.', validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='followup_gap_first_days',
            field=models.PositiveIntegerField(default=3, help_text='Quiet days before the FIRST follow-up is drafted.', validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='followup_gap_second_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after the first follow-up before the second.', validators=[django.core.validators.MaxValueValidator(365)]),
        ),
    ]
