# Generated by Django 5.2.12 on 2026-07-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0065_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='whatsapp_shortcuts_enabled',
            field=models.BooleanField(default=True, help_text="Show 'open WhatsApp with the message prefilled' shortcut buttons when in-app (Twilio) sending isn't active. Off = no personal-number outreach from this org."),
        ),
    ]
