# Generated by Django 5.2.12 on 2026-07-19 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0066_orgsettings_whatsapp_shortcuts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='followup_auto_generate',
            field=models.BooleanField(default=True, help_text='Draft follow-ups automatically every morning (only when AI follow-ups are enabled). Off = button-only.'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='followup_last_auto_run_at',
            field=models.DateTimeField(blank=True, help_text='When the scheduled run last generated for this org (guards against double runs).', null=True),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='followup_max_drafts_per_lead',
            field=models.PositiveIntegerField(default=3, help_text='Stop after this many follow-up drafts have been reviewed for one lead (sent or dismissed - a dismissal skips that stage).', validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
