# Generated by Django 5.2.12 on 2026-07-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0067_orgsettings_followup_auto_generate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='followup_auto_generate',
            field=models.BooleanField(default=False, help_text='Draft follow-ups automatically every morning (only when AI follow-ups are enabled). Off = button-only.'),
        ),
    ]
