# Generated by Django 5.2.12 on 2026-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0069_followup_auto_generate_opt_out_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='from_phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='to_phone',
            field=models.CharField(max_length=32),
        ),
    ]
