# Generated by Django 5.2.12 on 2026-07-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0071_quote_public_token_bookingsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
