# Generated by Django 5.2.16 on 2026-07-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0073_orgsettings_gratuity_default_pct_and_more'),
        ('users', '0007_alter_organisation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePresetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
                'unique_together': {('organisation', 'value')},
            },
        ),
    ]
