# Generated by Django 5.2.16 on 2026-07-30 23:07

from django.db import migrations, models


def backfill_standard_day(apps, schema_editor):
    """Give existing preset rows the default template values.

    An org that already had timeline steps (seeded by the signal, or backfilled
    with `seed_org_choices`) would otherwise have every step flagged out of the
    standard day, so "+ Build a run-of-show" would seed nothing. Matched on the
    stable `value` slug; a step the org invented itself has no default and is
    simply left out of the standard day for them to configure.
    """
    from bookings.defaults import TIMELINE_PRESET_DEFAULTS

    TimelinePresetOption = apps.get_model('bookings', 'TimelinePresetOption')
    for value, _label, in_day, offset in TIMELINE_PRESET_DEFAULTS:
        TimelinePresetOption.objects.filter(value=value).update(
            in_standard_day=in_day, standard_day_offset_minutes=offset,
        )


def unbackfill_standard_day(apps, schema_editor):
    # Reversible for local dev; the columns go with the AddField reversal anyway.
    TimelinePresetOption = apps.get_model('bookings', 'TimelinePresetOption')
    TimelinePresetOption.objects.update(
        in_standard_day=False, standard_day_offset_minutes=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0074_timelinepresetoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinepresetoption',
            name='in_standard_day',
            field=models.BooleanField(default=False, help_text='Seed this step when a booking builds its default run-of-show.'),
        ),
        migrations.AddField(
            model_name='timelinepresetoption',
            name='standard_day_offset_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes from meal service — negative is before (-150 = 2h30 before), 0 is meal service itself. Required to be seeded.', null=True),
        ),
        migrations.RunPython(backfill_standard_day, unbackfill_standard_day),
    ]
