# Generated by Django 5.2.16 on 2026-08-01 10:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0075_timelinepreset_standard_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='gratuity_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gratuity as a percentage of the subtotal (post-tax, never taxed)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service_charge_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service charge as a percentage of the subtotal', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
