# Generated by Django 5.2.16 on 2026-08-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0076_alter_quote_gratuity_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestyleoption',
            name='guests_choose',
            field=models.BooleanField(default=False),
        ),
    ]
