# Generated by Django 5.2.16 on 2026-08-08 08:30

import django.db.models.deletion
import users.model_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0078_servicestyle_guests_choose_backfill'),
        ('users', '0007_alter_organisation_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=16)),
                ('email_address', models.EmailField(max_length=254)),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_reconnect', 'Needs reconnect')], default='connected', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_mailboxes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connected_mailbox', to='users.organisation')),
            ],
            options={
                'verbose_name_plural': 'connected mailboxes',
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
