# Generated by Django 5.2.16 on 2026-08-08 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0079_connectedmailbox'),
        ('events', '0038_event_beo_revised_at_event_beo_revision'),
        ('users', '0007_alter_organisation_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='preferred_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='', help_text="This contact's preferred channel. Blank uses the organisation default.", max_length=10),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='default_client_channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', help_text='Channel preselected when messaging a client. Contacts can override it.', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='attachment_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], db_index=True, default='whatsapp', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='events.event'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='bookings.quote'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='to_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='from_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='bookings.lead'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('received', 'Received'), ('handed_off', 'Handed off'), ('to_send', 'To send'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='queued', max_length=15),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='to_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['quote', '-created_at'], name='bookings_wh_quote_i_2622d4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['event', '-created_at'], name='bookings_wh_event_i_9ef8ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('quote__isnull', False), ('event__isnull', False), _connector='OR'), name='clientmessage_has_a_parent'),
        ),
    ]
