# Generated by Django 5.2.16 on 2026-08-08 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0080_client_message_ledger'),
        ('events', '0038_event_beo_revised_at_event_beo_revision'),
        ('users', '0007_alter_organisation_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whatsappmessage',
            name='clientmessage_has_a_parent',
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('lead__isnull', False), ('quote__isnull', True)), models.Q(('event__isnull', True), ('lead__isnull', True), ('quote__isnull', False)), models.Q(('event__isnull', False), ('lead__isnull', True), ('quote__isnull', True)), _connector='OR'), name='clientmessage_has_exactly_one_parent'),
        ),
    ]
