"""Tax rates get a third decimal of percent.

`decimal_places=4` on a FRACTION is only two decimals of percent, so 8.875% — the
real, current New York City rate — could not be stored. The API rejected it
outright ("no more than 4 decimal places"), and the frontend's own rounding turned
it into 8.87% or 8.88%: a $2.50 error on a $50,000 booking, silently, in the
largest catering market this product targets.

Widening a Decimal is lossless for existing rows: 0.0850 reads back as 0.08500 and
every stored total still reconciles. Nothing is rewritten.
"""
# Generated by Django 5.2.16 on 2026-08-08 15:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0080_quote_total_invariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.20000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.20000'), help_text='Default tax rate as decimal (e.g. 0.20000 = 20%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.20000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
