# Generated by Django 5.2.16 on 2026-08-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0081_alter_invoice_tax_rate_and_more'),
        ('bookings', '0081_exactly_one_message_parent'),
    ]

    operations = [
    ]
