# Generated by Django 5.2.16 on 2026-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0082_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupdraft',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Email subject line. Empty for a WhatsApp draft, which has none.', max_length=300),
        ),
        migrations.AlterField(
            model_name='followupdraft',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20),
        ),
    ]
