# Generated by Django 6.1 on 2026-08-13 20:02

import django.db.models.deletion
import users.model_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0083_followupdraft_subject_alter_followupdraft_channel'),
        ('users', '0008_demorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_access_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_connections', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_connection', to='users.organisation')),
            ],
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
        migrations.CreateModel(
            name='ConnectedMetaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64)),
                ('page_name', models.CharField(max_length=255)),
                ('instagram_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('instagram_username', models.CharField(blank=True, default='', max_length=255)),
                ('page_access_token_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_meta_pages', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_meta_pages', to='users.organisation')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bookings.metaaccountconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'page_id'), name='unique_org_meta_page')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
