# Generated by Django 6.1 on 2026-08-16 20:20

import django.db.models.deletion
import users.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0084_metaaccountconnection_connectedmetapage'),
        ('users', '0008_demorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_leadgen_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='MetaWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('field', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_webhook_events', to='users.organisation')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['processed_at'], name='bookings_me_process_71546e_idx')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
