# Generated by Django 6.1 on 2026-08-16 21:36

import django.db.models.deletion
import users.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0085_lead_meta_leadgen_id_metawebhookevent'),
        ('users', '0008_demorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaIngestedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_ingested_refs', to='bookings.lead')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ingested_leads', to='users.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'leadgen_id'), name='unique_org_meta_leadgen')],
            },
            bases=(users.model_mixins.OrgScopedModel, models.Model),
        ),
    ]
