# Generated by Django 6.1 on 2026-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0086_metaingestedlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='proposal_agent_enabled',
            field=models.BooleanField(default=False, help_text='Let the AI draft full proposals (menu, plan, prose, pricing) from a lead. Always reviewed and never auto-sent.'),
        ),
        migrations.AddField(
            model_name='quote',
            name='proposal_assumptions',
            field=models.JSONField(blank=True, help_text='AI proposal assumptions [{field, value, reason}].', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='proposal_prose',
            field=models.JSONField(blank=True, help_text='AI proposal prose sections (client-facing).', null=True),
        ),
    ]
