# Generated by Django 6.1 on 2026-08-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0086_metaingestedlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedmetapage',
            name='default_product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_pages', to='bookings.productline'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='auto_assign_integration_leads',
            field=models.BooleanField(default=False),
        ),
    ]
