# Generated by Django 6.1 on 2026-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0087_connectedmetapage_default_product_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupdraft',
            name='kind',
            field=models.CharField(choices=[('followup', 'Follow-up'), ('first_response', 'First response')], db_index=True, default='followup', help_text='Whether this is a first-response draft or a quiet-lead follow-up.', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_first_response',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='first_response_enabled',
            field=models.BooleanField(default=False, help_text='Draft an AI first response for every new lead, for review (never auto-sent).'),
        ),
    ]
