# Generated by Django 6.1 on 2026-08-21 13:38

from django.db import migrations, models


def turn_on_for_existing_orgs(apps, schema_editor):
    """REL-515: first response is now ON by default. Existing orgs predate the
    new default (they were created with it off), so flip them on too — the owner
    asked for it on for everyone, not just orgs created from here on. It only
    fires for integration (Meta) leads and every draft is human-reviewed, and
    any org can switch it back off in Settings."""
    OrgSettings = apps.get_model('bookings', 'OrgSettings')
    OrgSettings.objects.filter(first_response_enabled=False).update(first_response_enabled=True)


def noop_reverse(apps, schema_editor):
    """No safe reverse: we can't tell which orgs were deliberately off before
    this ran, so leave values as they are on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0088_followupdraft_kind_lead_needs_first_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='first_response_enabled',
            field=models.BooleanField(default=True, help_text='Draft an AI first response for incoming integration leads, for review (never auto-sent).'),
        ),
        migrations.RunPython(turn_on_for_existing_orgs, noop_reverse),
    ]
