# Generated by Django 6.0.1 on 2026-03-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('dishes', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('gents', models.IntegerField(default=0)),
                ('ladies', models.IntegerField(default=0)),
                ('big_eaters', models.BooleanField(default=False)),
                ('big_eaters_percentage', models.FloatField(default=20.0, help_text='Percentage to increase all portions when big_eaters is on')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue_address', models.TextField(blank=True, help_text='Freeform address for ad-hoc locations')),
                ('event_type', models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('funeral', 'Funeral / Wake'), ('religious', 'Religious Event'), ('social', 'Social Gathering'), ('other', 'Other')], max_length=20)),
                ('service_style', models.CharField(blank=True, choices=[('buffet', 'Buffet'), ('plated', 'Plated / Sit-down'), ('stations', 'Food Stations'), ('family_style', 'Family Style'), ('boxed', 'Boxed / Individual'), ('canapes', 'Canapés'), ('mixed', 'Mixed Service')], max_length=20)),
                ('price_per_head', models.DecimalField(blank=True, decimal_places=2, help_text='Food/menu price per head', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='tentative', max_length=20)),
                ('setup_time', models.DateTimeField(blank=True, null=True)),
                ('guest_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('meal_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('guaranteed_count', models.IntegerField(blank=True, null=True)),
                ('final_count', models.IntegerField(blank=True, null=True)),
                ('final_count_due', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bookings.account')),
                ('based_on_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menutemplate')),
                ('dishes', models.ManyToManyField(blank=True, to='dishes.dish')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.contact')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.venue')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventConstraintOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_food_per_person_grams', models.FloatField(blank=True, null=True)),
                ('min_portion_per_dish_grams', models.FloatField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_override', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDishComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('portion_grams', models.FloatField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_comments', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'dish')},
            },
        ),
    ]
