# Generated by Django 6.0.1 on 2026-01-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('gents', models.IntegerField(default=0)),
                ('ladies', models.IntegerField(default=0)),
                ('big_eaters', models.BooleanField(default=False)),
                ('big_eaters_percentage', models.FloatField(default=20.0, help_text='Percentage to increase all portions when big_eaters is on')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventConstraintOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_food_per_person_grams', models.FloatField(blank=True, null=True)),
                ('max_total_protein_per_person_grams', models.FloatField(blank=True, null=True)),
                ('min_portion_per_dish_grams', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
