# Generated by Django 6.0.1 on 2026-01-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0002_alter_dish_protein_type'),
        ('events', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='based_on_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menutemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='dishes.dish'),
        ),
        migrations.AddField(
            model_name='eventconstraintoverride',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_override', to='events.event'),
        ),
    ]
