# Generated by Django 6.0.1 on 2026-02-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventconstraintoverride',
            name='max_total_protein_per_person_grams',
        ),
    ]
