# Generated by Django 6.0.1 on 2026-03-12 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='ladies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Food/menu price per head', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
    ]
