# Generated by Django 6.0.1 on 2026-02-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_remove_protein_per_gram'),
        ('events', '0003_remove_max_total_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDishComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('portion_grams', models.FloatField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_comments', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'dish')},
            },
        ),
    ]
