# Generated by Django 6.0.3 on 2026-03-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_created_by'),
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.organisation'),
        ),
    ]
