# Generated by Django 6.0.1 on 2026-02-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_quote_event'),
        ('events', '0004_eventdishcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.account'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('funeral', 'Funeral / Wake'), ('religious', 'Religious Event'), ('social', 'Social Gathering'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='final_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='final_count_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guaranteed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='service_style',
            field=models.CharField(blank=True, choices=[('buffet', 'Buffet'), ('plated', 'Plated / Sit-down'), ('stations', 'Food Stations'), ('family_style', 'Family Style'), ('boxed', 'Boxed / Individual'), ('canapes', 'Canapés'), ('mixed', 'Mixed Service')], max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='setup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='tentative', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.TextField(blank=True, help_text='Freeform address for ad-hoc locations'),
        ),
    ]
