# Generated by Django 6.0.1 on 2026-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_gents_alter_event_ladies_and_more'),
        ('events', '0005_make_org_nonnull'),
    ]

    operations = [
    ]
