# Generated by Django 6.0.1 on 2026-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Food/menu price per head', max_digits=10, null=True),
        ),
    ]
