# Generated by Django 6.0.1 on 2026-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_merge_20260312_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meal_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
