# Generated by Django 6.0.1 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_date',
            field=models.DateField(blank=True, help_text='Date the client confirmed/booked', null=True),
        ),
    ]
