# Generated by Django 5.2.12 on 2026-03-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_quote_product'),
        ('events', '0007_alter_event_id_alter_eventconstraintoverride_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.productline'),
        ),
    ]
