# Generated by Django 6.0.1 on 2026-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banquet_instructions',
            field=models.TextField(blank=True, help_text='Front-of-house/service team notes'),
        ),
        migrations.AddField(
            model_name='event',
            name='kitchen_instructions',
            field=models.TextField(blank=True, help_text='Cooking-specific notes for the kitchen team'),
        ),
        migrations.AddField(
            model_name='event',
            name='setup_instructions',
            field=models.TextField(blank=True, help_text='Logistics, table layout, client-provided items'),
        ),
    ]
