# Generated by Django 6.0.1 on 2026-03-13 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_banquet_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='events.event')),
            ],
            options={
                'ordering': ['arrangement_type'],
                'unique_together': {('event', 'arrangement_type')},
            },
        ),
    ]
