# Generated by Django 6.0.1 on 2026-03-13 22:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventbeverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='Whether tax applies to this event'),
        ),
        migrations.AddField(
            model_name='eventarrangement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='eventbeverage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
