# Generated by Django 6.0.1 on 2026-03-13 22:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_merge_20260312_2210'),
        ('events', '0012_event_is_taxable_eventarrangement_unit_price_and_more'),
        ('menus', '0004_merge_20260312_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Driver Food, Second Service', max_length=100)),
                ('guest_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('meal_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('based_on_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menutemplate')),
                ('dishes', models.ManyToManyField(blank=True, to='dishes.dish')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_meals', to='events.event')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventMealDishComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('portion_grams', models.FloatField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_comments', to='events.eventmeal')),
            ],
            options={
                'unique_together': {('meal', 'dish')},
            },
        ),
    ]
