# Generated by Django 6.0.1 on 2026-03-13 22:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventmeal_eventmealdishcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmeal',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
    ]
