# Generated by Django 5.2.12 on 2026-03-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_product'),
        ('events', '0015_perf_indexes'),
    ]

    operations = [
    ]
