# Generated by Django 5.2.12 on 2026-06-24 20:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_arrangements_beverages'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='event_org_date_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tax rate as a fraction (0.20 = 20%); applied only when is_taxable.', max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='eventmeal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventmeal',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventmealdishcomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
