# Generated by Django 5.2.12 on 2026-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rename_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
