# Generated by Django 5.2.12 on 2026-07-03 19:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rename_event_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))])),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.event')),
                ('received_by', models.ForeignKey(blank=True, help_text='Which team member took this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
