# Generated by Django 5.2.12 on 2026-07-07 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0053_productline_is_default'),
        ('events', '0023_eventpayment'),
        ('rules', '0006_guestsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGuestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_counts', to='events.event')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_counts', to='bookings.quote')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rules.guestsegment')),
            ],
            options={
                'ordering': ['segment__sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('quote__isnull', False)), models.Q(('event__isnull', False), ('quote__isnull', True)), _connector='OR'), name='bookingguestcount_exactly_one_parent'), models.UniqueConstraint(fields=('quote', 'segment'), name='uniq_quote_segment'), models.UniqueConstraint(fields=('event', 'segment'), name='uniq_event_segment')],
            },
        ),
    ]
