# Generated by Django 5.2.12 on 2026-07-11 20:19

import django.core.validators
from django.db import migrations, models


def backfill_guest_count(apps, schema_editor):
    """Existing events derived their headcount from gents+ladies; keep those
    numbers as the new primary guest_count. Splits stay untouched."""
    Event = apps.get_model('events', 'Event')
    Event.objects.update(
        guest_count=models.F('gents') + models.F('ladies'))


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_eventpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.RunPython(backfill_guest_count, migrations.RunPython.noop),
    ]
