# Generated by Django 5.2.12 on 2026-07-21 13:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_backfill_guest_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gratuity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='gratuity_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gratuity as a percentage of the subtotal (post-tax, never taxed)', max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='service_charge_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service charge as a percentage of the subtotal', max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='service_charge_taxable',
            field=models.BooleanField(default=True, help_text='Whether the service charge is added to the tax base'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
