# Generated by Django 5.2.16 on 2026-07-25 07:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_backfill_split_guest_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingguestcount',
            name='price_per_head',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
