# Generated by Django 5.2.16 on 2026-07-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0074_timelinepresetoption'),
        ('events', '0030_bookingguestcount_price_per_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimelineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0, help_text='Explicit run-of-show order — authoritative, so a caterer can place a row where they want it rather than by the clock.')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='events.event')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='bookings.quote')),
            ],
            options={
                'verbose_name_plural': 'booking timeline entries',
                'ordering': ['sort_order', 'time', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('quote__isnull', False)), models.Q(('event__isnull', False), ('quote__isnull', True)), _connector='OR'), name='timelineentry_exactly_one_parent')],
            },
        ),
    ]
