# Generated by Django 5.2.16 on 2026-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_bookingtimelineentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtimelineentry',
            name='date',
            field=models.DateField(blank=True, help_text="The day this step happens on. Null means the booking's event date, which is almost every step — set it only for the ones that aren't, like a load-in the afternoon before.", null=True),
        ),
    ]
