# Generated by Django 5.2.16 on 2026-07-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_timelineentry_date'),
        ('rules', '0007_guestsegment_counts_toward_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmeal',
            name='audience',
            field=models.CharField(choices=[('custom', 'Custom number'), ('everyone', 'Everyone'), ('guests', 'Guests only'), ('segment', 'Single segment')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingmeal',
            name='audience_segment',
            field=models.ForeignKey(blank=True, help_text='The single segment served when audience=segment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rules.guestsegment'),
        ),
    ]
