# Generated by Django 5.2.16 on 2026-07-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0073_orgsettings_gratuity_default_pct_and_more'),
        ('dishes', '0006_alter_dish_protein_type_alter_dishcategory_name_and_more'),
        ('events', '0033_bookingmeal_audience_bookingmeal_audience_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='events.event')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='bookings.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='eventdishcomment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.bookingcourse'),
        ),
        migrations.CreateModel(
            name='QuoteDishComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('portion_grams', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.bookingcourse')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_comments', to='bookings.quote')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookingcourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('quote__isnull', False)), models.Q(('event__isnull', False), ('quote__isnull', True)), _connector='OR'), name='bookingcourse_exactly_one_parent'),
        ),
        migrations.AlterUniqueTogether(
            name='quotedishcomment',
            unique_together={('quote', 'dish')},
        ),
    ]
