# Generated by Django 5.2.16 on 2026-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_event_gratuity_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdishcomment',
            name='choice_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdishcomment',
            name='is_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotedishcomment',
            name='choice_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotedishcomment',
            name='is_choice',
            field=models.BooleanField(default=False),
        ),
    ]
