# Generated by Django 5.2.16 on 2026-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_clear_unusable_segment_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beo_revised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Every existing event backfills to Rev 1 — the original issue, which is not
        # a revision of anything. Edited in place rather than stacked as a second
        # migration because this one has never been merged or deployed.
        migrations.AddField(
            model_name='event',
            name='beo_revision',
            field=models.IntegerField(default=1),
        ),
    ]
