"""Event tax rates get the same third decimal of percent as quotes.

Mirrors bookings.0081 — an event inherits its rate from the quote it came from, so
a rate the quote can hold and the event cannot would reintroduce the drift at
exactly the handover. Lossless widening; no row is rewritten.
"""
# Generated by Django 5.2.16 on 2026-08-08 15:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_event_total_invariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tax_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='Tax rate as a fraction (0.20 = 20%); applied only when is_taxable.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
