# Generated by Django 6.0.1 on 2026-03-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('protein_is_additive', models.BooleanField(default=False, help_text='If True, protein (meat) is added on top of the dish weight (e.g. rice dishes). If False, dish weight IS the protein weight (e.g. curry, dry/barbecue).')),
                ('pool', models.CharField(choices=[('protein', 'Protein'), ('accompaniment', 'Accompaniment'), ('dessert', 'Dessert'), ('service', 'Service')], default='protein', help_text='Which allocation pool this category belongs to', max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('qty', 'Quantity/Pieces')], default='kg', max_length=10)),
                ('baseline_budget_grams', models.FloatField(default=0, help_text='Standard budget for this category with 1 dish (per person)')),
                ('min_per_dish_grams', models.FloatField(default=0, help_text='Minimum viable portion for any single dish in this category')),
                ('fixed_portion_grams', models.FloatField(blank=True, help_text='For service pool only: fixed per-person amount', null=True)),
                ('addition_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding a dish in this category', max_digits=10)),
                ('removal_discount', models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing a dish from this category', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'dish categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protein_type', models.CharField(choices=[('chicken', 'Chicken'), ('mutton', 'Mutton'), ('lamb', 'Lamb'), ('beef', 'Beef'), ('veal', 'Veal'), ('fish', 'Fish'), ('none', 'None')], default='none', max_length=20)),
                ('default_portion_grams', models.FloatField(help_text='Baseline portion in grams')),
                ('popularity', models.FloatField(default=1.0, help_text='Relative popularity weight')),
                ('cost_per_gram', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('selling_price_per_gram', models.DecimalField(blank=True, decimal_places=4, help_text='Selling price per gram; auto-calculated unless overridden', max_digits=10, null=True)),
                ('selling_price_override', models.BooleanField(default=False, help_text='If True, selling_price_per_gram is manually set and not auto-calculated')),
                ('addition_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding this dish; auto-calculated unless overridden', max_digits=10)),
                ('removal_discount', models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing this dish; auto-calculated unless overridden', max_digits=10)),
                ('surcharge_override', models.BooleanField(default=False, help_text='If True, surcharges are manually set and not auto-calculated')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dishes.dishcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
