# Generated by Django 6.0.1 on 2026-01-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'dish categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protein_type', models.CharField(choices=[('chicken', 'Chicken'), ('lamb', 'Lamb'), ('beef', 'Beef'), ('fish', 'Fish'), ('seafood', 'Seafood'), ('pork', 'Pork'), ('none', 'None')], default='none', max_length=20)),
                ('default_portion_grams', models.FloatField(help_text='Baseline portion in grams')),
                ('protein_per_gram', models.FloatField(default=0.0, help_text='Protein density (0.0–1.0)')),
                ('popularity', models.FloatField(default=1.0, help_text='Relative popularity weight')),
                ('cost_per_gram', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dishes.dishcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
