# Generated by Django 6.0.1 on 2026-03-12 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='addition_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding this dish; auto-calculated unless overridden', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cost_per_gram',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='removal_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing this dish; auto-calculated unless overridden', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='selling_price_per_gram',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Selling price per gram; auto-calculated unless overridden', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='addition_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding a dish in this category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='baseline_budget_grams',
            field=models.FloatField(default=0, help_text='Standard budget for this category with 1 dish (per person)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='min_per_dish_grams',
            field=models.FloatField(default=0, help_text='Minimum viable portion for any single dish in this category', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='removal_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing a dish from this category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
