# Generated by Django 6.0.1 on 2026-01-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='protein_type',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('mutton', 'Mutton'), ('lamb', 'Lamb'), ('beef', 'Beef'), ('veal', 'Veal'), ('fish', 'Fish'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
