# Generated by Django 6.0.3 on 2026-03-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_categories', to='users.organisation'),
        ),
    ]
