# Generated by Django 6.0.1 on 2026-01-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_protein_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='protein_is_additive',
            field=models.BooleanField(default=False, help_text='If True, protein (meat) is added on top of the dish weight (e.g. rice dishes). If False, dish weight IS the protein weight (e.g. curry, dry/barbecue).'),
        ),
    ]
