# Generated by Django 6.0.1 on 2026-01-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_add_protein_is_additive'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='baseline_budget_grams',
            field=models.FloatField(default=0, help_text='Standard budget for this category with 1 dish (per person)'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='fixed_portion_grams',
            field=models.FloatField(blank=True, help_text='For service pool only: fixed per-person amount', null=True),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='min_per_dish_grams',
            field=models.FloatField(default=0, help_text='Minimum viable portion for any single dish in this category'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='pool',
            field=models.CharField(choices=[('protein', 'Protein'), ('dessert', 'Dessert'), ('service', 'Service')], default='protein', help_text='Which allocation pool this category belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('qty', 'Quantity/Pieces')], default='kg', max_length=10),
        ),
    ]
