# Generated by Django 6.0.1 on 2026-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_addition_surcharge_and_more'),
        ('dishes', '0003_make_org_nonnull'),
    ]

    operations = [
    ]
