# Generated by Django 6.0.1 on 2026-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dishcategory_baseline_budget_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='pool',
            field=models.CharField(choices=[('protein', 'Protein'), ('accompaniment', 'Accompaniment'), ('dessert', 'Dessert'), ('service', 'Service')], default='protein', help_text='Which allocation pool this category belongs to', max_length=20),
        ),
    ]
