# Generated by Django 6.0.1 on 2026-02-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_dishcategory_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='protein_per_gram',
        ),
    ]
