# Generated by Django 5.2.12 on 2026-07-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_dish_id_alter_dishcategory_id'),
        ('users', '0007_alter_organisation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='protein_type',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('beef', 'Beef'), ('pork', 'Pork'), ('turkey', 'Turkey'), ('lamb', 'Lamb'), ('mutton', 'Mutton'), ('veal', 'Veal'), ('fish', 'Fish'), ('seafood', 'Seafood'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='dishcategory',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_category_org_name'),
        ),
    ]
