# Generated by Django 6.0.1 on 2026-02-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_remove_protein_per_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='selling_price_override',
            field=models.BooleanField(default=False, help_text='If True, selling_price_per_gram is manually set and not auto-calculated'),
        ),
        migrations.AddField(
            model_name='dish',
            name='selling_price_per_gram',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Selling price per gram; auto-calculated unless overridden', max_digits=8, null=True),
        ),
    ]
