# Generated by Django 6.0.1 on 2026-02-27 20:45

from decimal import Decimal

from django.db import migrations


def populate_selling_prices(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    default_pct = Decimal('30.00')
    divisor = default_pct / Decimal('100')
    for dish in Dish.objects.exclude(cost_per_gram=0):
        dish.selling_price_per_gram = dish.cost_per_gram / divisor
        dish.save(update_fields=['selling_price_per_gram'])


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_dish_selling_price_override_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_selling_prices, migrations.RunPython.noop),
    ]
