# Generated by Django 6.0.1 on 2026-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_populate_selling_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cost_per_gram',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='selling_price_per_gram',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Selling price per gram; auto-calculated unless overridden', max_digits=10, null=True),
        ),
    ]
