# Generated by Django 6.0.1 on 2026-03-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_widen_cost_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='addition_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding a dish in this category', max_digits=10),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='removal_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing a dish from this category', max_digits=10),
        ),
    ]
