# Generated by Django 6.0.1 on 2026-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_add_surcharge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='addition_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding this dish. 0 = use category default.', max_digits=10),
        ),
        migrations.AddField(
            model_name='dish',
            name='removal_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing this dish. 0 = use category default.', max_digits=10),
        ),
    ]
