# Generated by Django 6.0.1 on 2026-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_add_dish_surcharge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='surcharge_override',
            field=models.BooleanField(default=False, help_text='If True, surcharges are manually set and not auto-calculated'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='addition_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head surcharge when adding this dish; auto-calculated unless overridden', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='removal_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-head discount when removing this dish; auto-calculated unless overridden', max_digits=10),
        ),
    ]
