# Generated by Django 6.0.1 on 2026-03-12 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per unit per event', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999.99'))]),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='quantity_out',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='quantity_returned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
