# Generated by Django 6.0.1 on 2026-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmentitem_rental_price_and_more'),
        ('equipment', '0003_make_org_nonnull'),
    ]

    operations = [
    ]
