# Generated by Django 6.0.1 on 2026-03-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('menu_type', models.CharField(choices=[('barat', 'Barat / Walima'), ('mehndi', 'Mehndi / Mayon'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('default_gents', models.IntegerField(default=50)),
                ('default_ladies', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuDishPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_grams', models.FloatField(help_text='Stored snapshot per-person portion in grams')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='menus.menutemplate')),
            ],
            options={
                'unique_together': {('menu', 'dish')},
            },
        ),
        migrations.CreateModel(
            name='MenuTemplatePriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_guests', models.PositiveIntegerField(help_text='Guest count threshold (e.g. 50, 100, 200)')),
                ('price_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='menus.menutemplate')),
            ],
            options={
                'ordering': ['min_guests'],
                'unique_together': {('menu', 'min_guests')},
            },
        ),
    ]
