# Generated by Django 6.0.1 on 2026-02-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutemplate',
            name='menu_type',
            field=models.CharField(choices=[('barat', 'Barat / Walima'), ('mehndi', 'Mehndi / Mayon'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuTemplatePriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_guests', models.PositiveIntegerField(help_text='Guest count threshold (e.g. 50, 100, 200)')),
                ('price_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='menus.menutemplate')),
            ],
            options={
                'ordering': ['min_guests'],
                'unique_together': {('menu', 'min_guests')},
            },
        ),
    ]
