# Generated by Django 6.0.1 on 2026-03-12 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutemplate',
            name='default_gents',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='default_ladies',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='menutemplatepricetier',
            name='price_per_head',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
    ]
