# Generated by Django 6.0.1 on 2026-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menutemplate_default_gents_and_more'),
        ('menus', '0003_make_org_nonnull'),
    ]

    operations = [
    ]
