# Generated by Django 6.0.1 on 2026-03-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity_enabled', models.BooleanField(default=True)),
                ('popularity_strength', models.FloatField(default=0.3, help_text='0 = ignore popularity, 1 = fully proportional')),
                ('protein_pool_ceiling_grams', models.FloatField(default=440, help_text='Hard max for total protein pool per person (grams)')),
                ('accompaniment_pool_ceiling_grams', models.FloatField(default=150, help_text='Hard max for accompaniment pool per person (grams)')),
                ('dessert_pool_ceiling_grams', models.FloatField(default=150, help_text='Hard max for dessert pool per person (grams)')),
                ('dish_growth_rate', models.FloatField(default=0.2, help_text='Each extra dish adds this fraction of baseline to category budget')),
                ('absent_redistribution_fraction', models.FloatField(default=0.7, help_text='Fraction of absent-category budget that redistributes to present categories (protein pool only, 0-1)')),
            ],
            options={
                'verbose_name': 'global config',
                'verbose_name_plural': 'global config',
            },
        ),
        migrations.CreateModel(
            name='GlobalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_food_per_person_grams', models.FloatField(default=1000)),
                ('min_portion_per_dish_grams', models.FloatField(default=30)),
            ],
            options={
                'verbose_name': 'global constraint',
                'verbose_name_plural': 'global constraints',
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('portion_multiplier', models.FloatField(help_text='1.0 for adult, 0.6 for child, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback profile if no other matches the menu')),
                ('protein_pool_ceiling_grams', models.FloatField(blank=True, help_text='Override protein pool ceiling for this tier (null = use global)', null=True)),
                ('accompaniment_pool_ceiling_grams', models.FloatField(blank=True, help_text='Override accompaniment pool ceiling for this tier (null = use global)', null=True)),
                ('dessert_pool_ceiling_grams', models.FloatField(blank=True, help_text='Override dessert pool ceiling for this tier (null = use global)', null=True)),
                ('categories', models.ManyToManyField(help_text='Which categories this profile is designed for', related_name='budget_profiles', to='dishes.dishcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_portion_grams', models.FloatField(blank=True, null=True)),
                ('max_portion_grams', models.FloatField(blank=True, null=True)),
                ('max_total_category_grams', models.FloatField(blank=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction_factor', models.FloatField(help_text='e.g. 0.85 = reduce by 15%')),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='dishes.dishcategory')),
            ],
        ),
    ]
