# Generated by Django 6.0.1 on 2026-01-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_food_per_person_grams', models.FloatField(default=560)),
                ('popularity_enabled', models.BooleanField(default=True)),
                ('popularity_strength', models.FloatField(default=0.3, help_text='0 = ignore popularity, 1 = fully proportional')),
            ],
            options={
                'verbose_name': 'global config',
                'verbose_name_plural': 'global config',
            },
        ),
        migrations.CreateModel(
            name='GlobalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_food_per_person_grams', models.FloatField(default=700)),
                ('max_total_protein_per_person_grams', models.FloatField(default=120)),
                ('min_portion_per_dish_grams', models.FloatField(default=30)),
            ],
            options={
                'verbose_name': 'global constraint',
                'verbose_name_plural': 'global constraints',
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('portion_multiplier', models.FloatField(help_text='1.0 for adult, 0.6 for child, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_grams', models.FloatField(help_text='Budget in grams for this category')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_portion_grams', models.FloatField(blank=True, null=True)),
                ('max_portion_grams', models.FloatField(blank=True, null=True)),
                ('max_total_category_grams', models.FloatField(blank=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction_factor', models.FloatField(help_text='e.g. 0.85 = reduce by 15%')),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='dishes.dishcategory')),
            ],
        ),
    ]
