# Generated by Django 6.0.1 on 2026-01-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_protein_type'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='total_food_per_person_grams',
        ),
        migrations.CreateModel(
            name='BudgetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback profile if no other matches the menu')),
                ('total_food_per_person_grams', models.FloatField(help_text='Total food budget per person for this profile')),
                ('categories', models.ManyToManyField(help_text='Which categories this profile is designed for', related_name='budget_profiles', to='dishes.dishcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetProfileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_grams', models.FloatField(help_text='Budget in grams for this category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rules.budgetprofile')),
            ],
            options={
                'unique_together': {('profile', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='CategoryBudget',
        ),
    ]
