# Generated by Django 6.0.1 on 2026-01-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_budget_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprofile',
            name='total_food_per_person_grams',
        ),
        migrations.AddField(
            model_name='budgetprofile',
            name='dessert_pool_ceiling_grams',
            field=models.FloatField(blank=True, help_text='Override dessert pool ceiling for this tier (null = use global)', null=True),
        ),
        migrations.AddField(
            model_name='budgetprofile',
            name='protein_pool_ceiling_grams',
            field=models.FloatField(blank=True, help_text='Override protein pool ceiling for this tier (null = use global)', null=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='dessert_pool_ceiling_grams',
            field=models.FloatField(default=150, help_text='Hard max for dessert pool per person (grams)'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='protein_pool_ceiling_grams',
            field=models.FloatField(default=440, help_text='Hard max for total protein pool per person (grams)'),
        ),
        migrations.DeleteModel(
            name='BudgetProfileEntry',
        ),
    ]
