# Generated by Django 6.0.1 on 2026-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_remove_budgetprofile_total_food_per_person_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetprofile',
            name='accompaniment_pool_ceiling_grams',
            field=models.FloatField(blank=True, help_text='Override accompaniment pool ceiling for this tier (null = use global)', null=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='accompaniment_pool_ceiling_grams',
            field=models.FloatField(default=150, help_text='Hard max for accompaniment pool per person (grams)'),
        ),
        migrations.AlterField(
            model_name='globalconstraint',
            name='max_total_food_per_person_grams',
            field=models.FloatField(default=1000),
        ),
    ]
