# Generated by Django 6.0.1 on 2026-02-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_budgetprofile_accompaniment_pool_ceiling_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='absent_redistribution_fraction',
            field=models.FloatField(default=0.7, help_text='Fraction of absent-category budget that redistributes (0-1)'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='dish_growth_rate',
            field=models.FloatField(default=0.2, help_text='Each extra dish adds this fraction of baseline to category budget'),
        ),
    ]
