# Generated by Django 6.0.1 on 2026-02-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_globalconfig_absent_redistribution_fraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconstraint',
            name='max_total_protein_per_person_grams',
        ),
    ]
