# Generated by Django 5.2.12 on 2026-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_guestsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsegment',
            name='counts_toward_total',
            field=models.BooleanField(default=True, help_text='True: part of the guest count (Adults, Kids). False: an additional cover billed separately (Vendor meals), not counted in the headline guest number.'),
        ),
    ]
