# Generated by Django 6.0.1 on 2026-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_remove_max_total_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='category_budget_cap_multiplier',
            field=models.FloatField(blank=True, default=1.5, help_text='Cap each category budget at grown_budget × this multiplier. Limits redistribution inflation. Null = disabled.', null=True),
        ),
    ]
