# Generated by Django 6.0.1 on 2026-02-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_globalconfig_category_budget_cap_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='category_budget_cap_multiplier',
        ),
    ]
