# Generated by Django 5.2.16 on 2026-08-02 18:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_guestsegment_counts_toward_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsegment',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Charge vs base per-head price (1.0 full, 0.5 half).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
