# Generated by Django 6.0.1 on 2026-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_remove_globalconfig_category_budget_cap_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='absent_redistribution_fraction',
            field=models.FloatField(default=0.7, help_text='Fraction of absent-category budget that redistributes to present categories (protein pool only, 0-1)'),
        ),
    ]
