# Generated by Django 5.2.12 on 2026-06-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comped',
            field=models.BooleanField(default=False, help_text='Complimentary free access (friendly/beta/grandfathered). Grants access regardless of subscription status.'),
        ),
    ]
