# Generated by Django 5.2.12 on 2026-07-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_grandfather_existing_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(help_text='ISO 4217, e.g. PKR, USD, GBP', max_length=3)),
                ('currency_symbol', models.CharField(default='', max_length=8)),
                ('countries', models.JSONField(blank=True, default=list, help_text='ISO 3166-1 alpha-2 codes in this region, e.g. ["PK","IN","BD"].')),
                ('is_default', models.BooleanField(default=False, help_text='The fallback region for countries not listed anywhere. Exactly one.')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('display_amount', models.DecimalField(decimal_places=2, help_text="Shown in the UI. Must match the Stripe Price's amount.", max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='payments.plan')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='payments.pricingregion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'region'), name='uniq_plan_region_price')],
            },
        ),
    ]
