# Generated by Django 6.0.1 on 2026-03-12 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_laborrole_color_sort_order_allocationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrule',
            name='guests_per_staff',
            field=models.IntegerField(help_text='e.g. 30 means 1 staff per 30 guests', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='allocationrule',
            name='minimum_staff',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='laborrole',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='break_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override default role rate', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
    ]
