# Generated by Django 6.0.3 on 2026-03-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_laborrole_color_sort_order_allocationrule'),
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrole',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_roles', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='users.organisation'),
        ),
    ]
