# Generated by Django 6.0.1 on 2026-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_allocationrule_guests_per_staff_and_more'),
        ('staff', '0004_make_org_nonnull'),
    ]

    operations = [
    ]
