# Generated by Django 5.2.12 on 2026-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_merge_20260312_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
