# Generated by Django 5.2.12 on 2026-07-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_split_staff_names'),
        ('users', '0007_alter_organisation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrule',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='users.organisation'),
        ),
        migrations.AlterField(
            model_name='laborrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='laborrole',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_laborrole_org_name'),
        ),
    ]
