"""
Django settings for portioning project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "The SECRET_KEY environment variable is required. "
        "Set it in your .env file or environment."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Auto-seed a starter catalog (dishes/menus/add-ons/rules/choice options) into
# every new organisation on creation, so a fresh tenant's forms aren't empty.
# On for dev/prod; OFF under the test runner so the ~700 org-creating tests stay
# fast and in control of their own data. Override via env if needed.
SEED_STARTER_CATALOG_ON_ORG_CREATE = os.environ.get(
    'SEED_STARTER_CATALOG_ON_ORG_CREATE',
    'False' if 'test' in sys.argv else 'True',
).lower() in ('true', '1', 'yes')

# The "operations" suite — portioning calculator, kitchen events, staffing and
# the portioning Help explainer — is hidden from the product for now: the
# current story is sharply revenue/CRM-focused and these features are
# reintroduced together at a later stage. This flag gates only the USER-FACING
# surfaces (nav items, /calculate, /kitchen, /staff, /help, related CTAs) — the
# portioning engine still runs internally when a signed quote becomes an event.
# Equipment and Menu Templates are NOT gated here: they stay available to admins
# via the admin menu. Default OFF; flip to launch. Echoed to the frontend via
# the /bookings/settings/ payload as `operations_enabled`.
OPERATIONS_ENABLED = os.environ.get(
    'OPERATIONS_ENABLED', 'False',
).lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
]
if not DEBUG and ALLOWED_HOSTS == ['localhost', '127.0.0.1']:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must be explicitly set in production (DEBUG=False)."
    )

# Hostnames that mean "this machine" — fine as a dev default, never a public URL.
_LOCAL_HOSTNAMES = frozenset({'localhost', '127.0.0.1', '::1', '0.0.0.0'})


def _require_public_url(name, value, *, debug):
    """Refuse to boot on a public URL that still points at localhost (REL-476).

    These settings are not merely redirect targets: FRONTEND_BASE_URL builds the
    booking link that gets *emailed to a client*. Left at its dev default in
    production the app stays healthy, the send reports success, and the client
    receives a link only the sender's own machine can open. Nothing downstream
    can detect that, so the check has to happen before anything serves.

    `debug` is a parameter rather than a read of the module global so the rule
    itself is testable without reimporting settings.
    """
    if debug:
        return value
    parsed = urlparse((value or '').strip())
    if parsed.scheme not in ('http', 'https') or not parsed.hostname:
        raise ImproperlyConfigured(
            f"{name} must be an absolute URL including the scheme "
            f"(e.g. https://example.com) when DEBUG=False. Got: {value!r}"
        )
    if parsed.hostname.lower() in _LOCAL_HOSTNAMES:
        raise ImproperlyConfigured(
            f"{name} still points at {parsed.hostname} with DEBUG=False. It is used to "
            f"build URLs that leave this server — including the booking links sent to "
            f"clients — so a localhost value produces links nobody else can open. "
            f"Set it to this deployment's public URL."
        )
    return value


def _require_token_encryption_key(value, *, debug):
    """Refuse to boot in production without a dedicated mailbox-token key (REL-487).

    Left unset, `bookings.services.encryption` falls back to a SECRET_KEY-derived
    key. That fallback is convenient in dev and a real exposure in production: it
    makes one value both the JWT/OAuth-state signing key and the key to every
    caterer's Gmail/Outlook refresh token, so a single leak forges sessions *and*
    decrypts live mailbox credentials. They should fail independently.

    To adopt the key on an environment that has been running on the fallback,
    list the current SECRET_KEY in TOKEN_ENCRYPTION_KEY_FALLBACKS — fallbacks
    decrypt only, so existing ciphertext keeps reading while every new write goes
    out under the dedicated key.

    `debug` is a parameter rather than a read of the module global so the rule is
    testable without reimporting settings.
    """
    if debug:
        return value
    if not (value or '').strip():
        raise ImproperlyConfigured(
            "TOKEN_ENCRYPTION_KEY must be set when DEBUG=False. Without it, "
            "mailbox refresh tokens are encrypted under a SECRET_KEY-derived "
            "key, so leaking SECRET_KEY would also expose every connected "
            "mailbox. Generate one with "
            "`python -c \"from cryptography.fernet import Fernet; "
            "print(Fernet.generate_key().decode())\"`. If this environment has "
            "been running without it, also set TOKEN_ENCRYPTION_KEY_FALLBACKS "
            "to the current SECRET_KEY so existing tokens still decrypt."
        )
    return value

# ── Platform integrations (shared across all orgs) ──
# Twilio is the platform's single account; each org configures only its own
# WhatsApp sender number (OrgSettings.twilio_whatsapp_number). LLM keys are
# likewise platform-level — orgs only toggle AI features on/off.
# How long any outbound client message (email via the mailbox, WhatsApp via
# Twilio) may spend talking to its provider. Deliberately short: a send can run
# inside a *client's* request — the signed-copy send happens while the customer
# waits on the public sign page — and nothing in that response depends on it
# finishing. A slow provider should cost them a few seconds, not a timeout
# page for a booking they successfully signed (REL-474).
OUTBOUND_SEND_TIMEOUT = int(os.environ.get('OUTBOUND_SEND_TIMEOUT', '8'))

TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')

# One API key per LLM provider; only providers actually in use need a key.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Shared secret for the scheduled-jobs endpoint (GitHub Actions cron). Unset = endpoint disabled.
CRON_SECRET = os.environ.get('CRON_SECRET', '')

# ── Client email: send from the caterer's own mailbox (REL-460) ──
# Each org connects its own Gmail/Outlook account by OAuth; the platform holds
# only send-scoped tokens and never a mailbox password. The OAuth *apps* are
# platform-level, so the client id/secret pairs live here.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
MS_OAUTH_CLIENT_ID = os.environ.get('MS_OAUTH_CLIENT_ID', '')
MS_OAUTH_CLIENT_SECRET = os.environ.get('MS_OAUTH_CLIENT_SECRET', '')
# Public origin the provider redirects back to — must exactly match the
# redirect URI registered in Google Cloud Console / Entra. Prod:
# https://catering.relogue.com
OAUTH_REDIRECT_BASE = _require_public_url(
    'OAUTH_REDIRECT_BASE',
    os.environ.get('OAUTH_REDIRECT_BASE', 'http://localhost:8000'),
    debug=DEBUG,
)
# Key for encrypting mailbox refresh tokens at rest. REQUIRED when DEBUG=False
# (see _require_token_encryption_key); in dev it falls back to a SECRET_KEY-
# derived key. Having its own key means rotating SECRET_KEY doesn't make every
# caterer reconnect — and that the JWT signing key isn't also the key to their
# mailboxes. When set it is used alone; to change keys without stranding
# existing ciphertext, list the previous one (or SECRET_KEY) in the fallbacks,
# which decrypt only.
TOKEN_ENCRYPTION_KEY = _require_token_encryption_key(
    os.environ.get('TOKEN_ENCRYPTION_KEY', ''), debug=DEBUG,
)
TOKEN_ENCRYPTION_KEY_FALLBACKS = os.environ.get('TOKEN_ENCRYPTION_KEY_FALLBACKS', '')

# Capture outgoing client email instead of calling a provider, for local dev and
# tests. Off in production: without this guard a missing OAuth client id would
# silently turn every real send into a no-op that still reports success.
EMAIL_FAKE_TRANSPORT = os.environ.get(
    'EMAIL_FAKE_TRANSPORT',
    'True' if (DEBUG or 'test' in sys.argv) else 'False',
).lower() in ('true', '1', 'yes')

# ── Meta (Facebook/Instagram) lead capture (REL-506) ──
# One platform-level Meta app (Business type) fronts every org: each org connects
# its own Page(s) by OAuth (Facebook Login for Business) and we store per-Page
# tokens encrypted, reusing TOKEN_ENCRYPTION_KEY and OAUTH_REDIRECT_BASE above.
# The app id/secret are platform credentials, so they live here; the secret is
# never sent to the frontend. Provisioned in REL-505.
META_APP_ID = os.environ.get('META_APP_ID', '')
META_APP_SECRET = os.environ.get('META_APP_SECRET', '')
# Launch flag gating the whole Meta integration surface (Settings card, nav,
# and the connect endpoints), same pattern as OPERATIONS_ENABLED. Default OFF;
# echoed to the frontend via /bookings/settings/ as `meta_leads_enabled`.
META_LEADS_ENABLED = os.environ.get(
    'META_LEADS_ENABLED', 'False',
).lower() in ('true', '1', 'yes')

# Which model each AI task runs on, as 'provider:model' — see portioning/llm.py.
# Switching supplier or model per task is a one-env-var change, nothing else.
LLM_FOLLOWUP_DRAFTER = os.environ.get('LLM_FOLLOWUP_DRAFTER', 'openai:gpt-5.4-nano')
# Drafts the client-facing message a rep reviews before sending (REL-445). Same
# cheap-and-fast tier as follow-ups; a human always reads this one before it goes.
LLM_CLIENT_MESSAGE_DRAFTER = os.environ.get(
    'LLM_CLIENT_MESSAGE_DRAFTER', 'openai:gpt-5.4-nano',
)
# The walking-skeleton agent's LLM node (REL-510 / agents app). A cheap-and-fast
# tier is fine — it drafts one clarifying question a human then answers.
LLM_AGENT_SKELETON = os.environ.get('LLM_AGENT_SKELETON', 'openai:gpt-5.4-nano')
# The eval harness's inquiry-extraction target (REL-511). The first evaluatable
# structured output; REL-413's proposal builder reuses/extends it.
LLM_AGENT_INQUIRY_EXTRACTION = os.environ.get(
    'LLM_AGENT_INQUIRY_EXTRACTION', 'openai:gpt-5.4-nano',
)
# Optional LLM-as-judge for prose/tone eval cases (REL-511). Only invoked by
# cases that ask for it; deterministic assertion evaluators need no LLM.
LLM_AGENT_EVAL_JUDGE = os.environ.get('LLM_AGENT_EVAL_JUDGE', 'openai:gpt-5.4-nano')

# ── Agent tracing (REL-511, LangSmith) — dev/eval ONLY ──
# LangSmith is a third-party SaaS and agent traces would carry org customer data
# (lead names, message content), so tracing is OFF by default and enabled only by
# an explicit env var. It is deliberately NOT set in DigitalOcean prod; revisit
# (redaction / self-hosted Langfuse) before any prod enablement. When enabled,
# agents/tracing.py exports the LangChain/LangSmith env so LangGraph auto-traces.
LANGSMITH_TRACING = os.environ.get('LANGSMITH_TRACING', 'False').lower() in ('true', '1', 'yes')
LANGSMITH_API_KEY = os.environ.get('LANGSMITH_API_KEY', '')
LANGSMITH_PROJECT = os.environ.get('LANGSMITH_PROJECT', 'relogue-agents')
LANGSMITH_ENDPOINT = os.environ.get('LANGSMITH_ENDPOINT', 'https://api.smith.langchain.com')

# Where LangGraph persists agent checkpoints in dev (SQLite). Prod uses the
# Postgres checkpointer over DATABASE_URL instead — see agents/checkpointer.py.
# Kept out of db.sqlite3 so it never collides with Django's test database.
AGENT_CHECKPOINT_DB = os.environ.get(
    'AGENT_CHECKPOINT_DB', str(BASE_DIR / 'agent_checkpoints.sqlite3'),
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'dishes',
    'menus',
    'rules',
    'events',
    'calculator',
    'bookings',
    'staff',
    'equipment',
    'users',
    'payments',
    'agents',
    'rest_framework_simplejwt.token_blacklist',
    'axes',
]

AUTH_USER_MODEL = "users.User"

# ── Brute-force protection (REL-485) ──
# AxesStandaloneBackend must come first: it is a gate, not a backend that can
# authenticate anyone. It raises for a locked-out identity before ModelBackend
# gets to spend a password hash on the attempt.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Lock the ACCOUNT, not the IP. Credential-stuffing against one known email is
# distributed by definition — a per-IP limit is one rented proxy away from
# useless, while a per-account limit costs the attacker the thing they cannot
# spread across hosts.
AXES_LOCKOUT_PARAMETERS = ['username']
AXES_FAILURE_LIMIT = int(os.environ.get('AXES_FAILURE_LIMIT', '8'))
# Auto-expiring, so a locked-out colleague is never waiting on an admin. Long
# enough that 8-per-30-minutes is hopeless for guessing, short enough that
# someone who genuinely forgot their password can retry over a coffee.
AXES_COOLOFF_TIME = timedelta(
    minutes=int(os.environ.get('AXES_COOLOFF_MINUTES', '30')),
)
AXES_RESET_ON_SUCCESS = True
# The API authenticates with `email=`, and a DRF JSON body never populates
# request.POST — so the form-field lookup axes uses by default would read every
# attempt as an empty username and lock one shared bucket for all accounts.
AXES_USERNAME_CALLABLE = 'users.throttling.axes_username'
AXES_USERNAME_FORM_FIELD = 'email'
# Only ever trust the hop our own proxy appended; see users.throttling.
AXES_IPWARE_PROXY_COUNT = int(os.environ.get('NUM_PROXIES', '1'))
AXES_IPWARE_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']
# Never silently pass an attempt through because the lockout store is unhappy.
AXES_ENABLE_ACCESS_FAILURE_LOG = True

# axes.W006 objects that AXES_LOCKOUT_PARAMETERS omits 'ip_address'. That is the
# point: including it would let an attacker with a pool of addresses keep getting
# a fresh allowance for the same account, which is precisely the credential-
# stuffing shape this exists to stop. The accepted cost is that someone can
# deliberately lock a colleague out by failing their login on purpose —
# time-boxed by AXES_COOLOFF_TIME, which expires on its own.
SILENCED_SYSTEM_CHECKS = ['axes.W006']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.OrgMiddleware',
    'payments.middleware.SubscriptionGateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.CSPMiddleware',
    # Last: it turns the PermissionDenied that AxesStandaloneBackend raises for
    # a locked-out identity into a real lockout response, so it has to wrap the
    # view that calls authenticate().
    'axes.middleware.AxesMiddleware',
]

# Stripe (SaaS subscription billing — see the `payments` app)
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_ID = os.environ.get('STRIPE_PRICE_ID', '')  # default plan's Price id
# Where Checkout / Billing Portal redirect back to (the Next.js app).
FRONTEND_BASE_URL = _require_public_url(
    'FRONTEND_BASE_URL',
    os.environ.get('FRONTEND_BASE_URL', 'http://localhost:3000'),
    debug=DEBUG,
)
# Length of the no-card free trial granted to every new org on sign-up.
DEFAULT_TRIAL_DAYS = int(os.environ.get('DEFAULT_TRIAL_DAYS', '7'))

# CORS
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
]
CORS_ALLOW_CREDENTIALS = True
# A file download is fetched as a blob, and a blob URL carries no Content-Disposition
# — so `a.download` is the only filename the browser ever sees. Without this the
# frontend can't read the name the server chose and has to guess one, which is how
# every BEO revision would have landed as the same "BEO-8.pdf" (REL-444).
CORS_EXPOSE_HEADERS = ['Content-Disposition']

# CSRF — trust the same origins as CORS, and expose the cookie to the frontend
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS[:]
CSRF_COOKIE_HTTPONLY = False  # Frontend JS needs to read it to send X-CSRFToken header
CSRF_COOKIE_SAMESITE = 'Lax'

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # Overridable by environment so a test stack can lift them, and ONLY for
    # that: the defaults are the production values and nothing sets these vars
    # in a deployment. The e2e suite drives ~30 real logins from one IP in two
    # minutes, which is indistinguishable from credential stuffing to a limit
    # sized for real humans — it crossed 100/hour once the suite grew past ~25
    # specs, and every PR after that would have failed at whichever spec ran
    # last. Raising the ceiling for CI is right; lowering it for clients is not.
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_ANON', '100/hour'),
        'demo_requests': os.environ.get('THROTTLE_DEMO_REQUESTS', '10/hour'),
        'user': os.environ.get('THROTTLE_USER', '1000/hour'),
        # Cheap first line in front of the per-account lockout: it costs an
        # attacker nothing to be locked out of an account they don't own, but
        # it does cost them request volume. Tunable for the same reason as the
        # three above — and because the key is an address, which a whole office
        # behind one NAT shares.
        'login': os.environ.get('LOGIN_RATE_LIMIT', '10/min'),
        'token_refresh': os.environ.get('TOKEN_REFRESH_RATE_LIMIT', '30/min'),
    },
    # How many proxies sit in front of the app, so the throttle key is the hop
    # OUR proxy appended rather than whatever the client put in X-Forwarded-For.
    # Left unset, DRF keys on the entire client-supplied header, and varying it
    # by one byte per request mints a fresh bucket every time — the limit may as
    # well not exist (REL-485).
    'NUM_PROXIES': int(os.environ.get('NUM_PROXIES', '1')),
    'EXCEPTION_HANDLER': 'portioning.exception_handler.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'bookings.pagination.OptionalPagination',
    'PAGE_SIZE': 50,
}

# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': not DEBUG,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

ROOT_URLCONF = 'portioning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portioning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        # Reuse DB connections across requests instead of opening a new one
        # (and paying the TCP+TLS handshake) every request. Huge latency win on
        # managed Postgres; ignored harmlessly by SQLite in dev.
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/api/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ── Logging ──
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'tenant': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'tenant',
        },
    },
    'loggers': {
        # LLM call timings (portioning.llm) + agent activity (bookings.*)
        'portioning': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'bookings': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tenant.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'tenant.audit': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ── Production security settings ──
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
