# Generated by Django 6.0.1 on 2026-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_reminder'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_lines',
            field=models.ManyToManyField(blank=True, related_name='salespeople', to='bookings.productline'),
        ),
    ]
