# Generated by Django 6.0.1 on 2026-03-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_product_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('chef', 'Chef'), ('salesperson', 'Salesperson')], default='salesperson', max_length=20),
        ),
    ]
