# Generated by Django 6.0.3 on 2026-03-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_migrate_staff_to_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(default='PK', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(default='default', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
