# Generated by Django 5.2.12 on 2026-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_org_enrich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('chef', 'Chef'), ('salesperson', 'Salesperson')], default='salesperson', max_length=20),
        ),
    ]
