# Generated by Django 5.2.12 on 2026-07-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=models.CharField(default='US', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
    ]
